### ISSUE TITLE
Publish on pypi

### ISSUE THREAD

**Issue by gfronza** [gfronza/rabbitmq-alert#12]

**Comment by josegonzalez** [comment]
Is this done? I can help set it up for you if not.

**Comment by mylk** [comment]
Hello @josegonzalez 

Sorry for my late response.
We have made a few changes to make that possible, but it hasn't been published yet.

Any help would really be appreciated.

**Comment by josegonzalez** [comment]
Want to give me repo and pypi access?

**Comment by mylk** [comment]
Hey @josegonzalez.

It would be great if you could share your experience with publishing at pypi.
I'm a bit unsure if everything is properly set-up at the project.
Can you take a look?

Also, do you think we could place the example.ini at, lets say, /etc/rabbitmq-alert/example.ini?

PRs are always welcome.
Thanks

**Comment by josegonzalez** [comment]
If you give me commit bit on the repo and (assuming you have the pypi project up) access to the pypi project, I'll set everything up for you.

**Comment by mylk** [comment]
I don't think I have enough permissions on the repo and the owner isn't active on the project at this time.
That's why I proposed fork and PR.

Thanks

**Comment by josegonzalez** [comment]
Got it, I'll take a look and push changes in a branch.

**Comment by mylk** [comment]
Published on PyPi:

https://pypi.python.org/pypi/rabbitmq-alert
