### ISSUE TITLE
Different alert conditions for different queues

### ISSUE THREAD

**Issue by josegonzalez** [gfronza/rabbitmq-alert#13]
Would be great to be able to specify conditions on a per-queue basis. Something like the following:

```
[QueueConditions:queue-name]
# conditions here
```

**Comment by mylk** [comment]
Hey @josegonzalez 

Sounds like a nice idea. I'm gonna take a look and get back with an update.

**Comment by gfronza** [comment]
@mylk @josegonzalez I'm in the middle of a overseas trip right now, but when I get back home I'll set up the pypi project and give you guys permission accordingly ok?

Thank you all

**Comment by josegonzalez** [comment]
<3 Enjoy your trip!

**Comment by mylk** [comment]
Hey @josegonzalez 

I've got some job done about this. It's not so pretty but it works.

Gonna test it on a real queue today and if ready, i'll push it.

**Comment by mylk** [comment]
Closed by 527c9389d89894b30e3ae8207e56ddd66ef3a18d
