### ISSUE TITLE
Separate number of consumers and number of connections

### ISSUE THREAD

**Issue by velika12** [gfronza/rabbitmq-alert#17]
Hello,

I have noticed that you get number of connected consumers this way
```
def check_connection_conditions(self, options):
        queue = options["queue"]
        url = "http://%s:%s/api/connections" % (options["host"], options["port"])
        data = self.send_request(url, options)

        consumers_connected = len(data)

        consumers_con = options["conditions"][queue].get("consumers_connected")

        if consumers_con is not None and consumers_connected < consumers_con:
            self.send_notification(options, "consumers_connected < %s" % str(consumers_con))
```

But number of connected consumers and number of connections to server are not always the same. For example, in my project there are 11 connections and only 4 consumers.

**Comment by mylk** [comment]
Hello @velika12.

Thanks for noticing. It seems that there is a more appropriate api endpoint to get this information. I'll provide a fix soon.
