### ISSUE TITLE
Create a docker image

### ISSUE THREAD

**Issue by velika12** [gfronza/rabbitmq-alert#18]
Hello!
I think it would be nice if there existed a docker image of the project on Docker hub. What do you think of this idea?

**Comment by mylk** [comment]
Hello @velika12.

Thats a great idea!

The past few days I experimented a bit and soon there will be a docker image of the application in Docker Hub!

I'll keep you updated as soon as the image gets added.

**Comment by mylk** [comment]
Hey @velika12.

I'm happy to announce that the project can run in a container too.
Thats the dockerhub repo:

https://hub.docker.com/r/mylkoh/rabbitmq-alert/

For any additional information, take a look at the Readme file.

Thanks for your suggestion!
