### ISSUE TITLE
[Email] is mandatory ?

### ISSUE THREAD

**Issue by barisvelioglu** [gfronza/rabbitmq-alert#19]
I only want to use it as Slack message but when build a config.ini like below 

> [Server]
> host=localhost
> port=5672
> username=guest
> password=guest
> vhost=%2f
> queues=tasks
> check_rate=10
> 
> [Conditions]
> ready_queue_size=0
> unack_queue_size=0
> total_queue_size=0
> consumers_connected=1
> open_connections=1
> nodes_running=1
> node_memory_used=100
> 
> [Slack]
> url=https://hooks.slack.com/services/xoxb-xxxxxx
> channel=tasks
> username=rabbitmq-barisv-bot

and tries to run it. It says

> Traceback (most recent call last):
  File "./rabbitmqalert.py", line 160, in <module>
    main()
  File "./rabbitmqalert.py", line 135, in main
    options = optionsresolver.OptionsResover.setup_options()
  File "/my-plugins/rabbitmq-alert/rabbitmqalert/optionsresolver.py", line 68, in setup_options
    options["email_to"] = cli_arguments.email_to or config_file_options.get("Email", "to")
  File "/usr/lib/python2.7/ConfigParser.py", line 607, in get
    raise NoSectionError(section)
ConfigParser.NoSectionError: No section: 'Email'

**Comment by mylk** [comment]
Hello @barisvelioglu.
You are right, none of the notification methods should be mandatory in the configuration file.

I'll provide a fix very soon.

Thanks for your time.

**Comment by mylk** [comment]
Hello again @barisvelioglu.

I created a, somewhat, hotfix as I'm already in the process of refactoring the process of parsing the options, but as said, its still in progress.

Please, get the new version. I would suggest throught ```pip`` (advise the README file of the project).

Thank you.
