### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by Emi94** [gfronza/rabbitmq-alert#31]
Hi,

I'm asking as I don't see activity on this repo for more than a year.

Also, I wanted to test this on a server running ubuntu 20.04, but when I ran `pip3 install rabbit-alert` it threw these errors:

```
ERROR: Could not find a version that satisfies the requirement rabbit-alert (from versions: none)
ERROR: No matching distribution found for rabbit-alert
```

Is it not supported for ubuntu 20.04 (python3) or am I missing something?

**Comment by mylk** [comment]
Hello @Emi94.

The project was lower in my priorities than it should be,
but I will catch up with everything that is pending soon.

I'll check your case too and come up with any possible solution as nothing pops into my head right now.

**Comment by mylk** [comment]
Hello again @Emi94.

Sorry, I didn't notice at first. The package name is `rabbitmq-alert` not `rabbit-alert` (check pypi at https://pypi.org/project/rabbitmq-alert/).
So, the command you should be using to install the package is the following:

```
pip3 install rabbitmq-alert
```

Thanks.
