### ISSUE TITLE
Check multiple queues

### ISSUE THREAD

**Issue by mylk** [gfronza/rabbitmq-alert#8]
It would be nice to be able to check multiple queues for the conditions instead of a single.

**Comment by mylk** [comment]
Hello @gfronza.

If you too think this would be useful, please check #9.

Thank you.

**Comment by gfronza** [comment]
Thanks for your contribution. Since you did most of the work in this repository, I added you as a collaborator so you can keep up the good work. 🍻

**Comment by mylk** [comment]
Thanks @gfronza thats really kind.

I will be using rabbitmq-alert it on production soon, so I thought I could contribute a bit :-)
